services:
  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - 5432:5432

  redis:
    image: 'redis'
    ports:
      - '6379:6379'

  influxdb:
    image: 'influxdb'
    ports:
      - 8181:8181

  emqx:
    image: emqx/emqx
    ports:
      - 1883:1883
      - 18083:18083
