# Power management 
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y

# Logs / Debug

CONFIG_LOG=n
CONFIG_CONSOLE=n

# Peripherals

CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_BME680=y

# Sensor configs

CONFIG_BME680_PRESS_OVER_1X=y

